# Generated by Django 2.1.15 on 2023-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hanghoa',
            fields=[
                ('ma_hh', models.CharField(db_column='Ma_HH', max_length=10, primary_key=True, serialize=False)),
                ('ten_hh', models.CharField(db_column='Ten_HH', max_length=50)),
                ('so_luong', models.IntegerField(db_column='So_luong')),
                ('don_gia', models.DecimalField(db_column='Don_gia', decimal_places=0, max_digits=12)),
            ],
            options={
                'db_table': 'HangHoa',
            },
        ),
    ]
