# Generated by Django 2.1.15 on 2023-11-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanghoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanghoa',
            name='ma_hh',
            field=models.CharField(db_column='Ma_hang_hoa', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='ten_hh',
            field=models.CharField(db_column='Ten_hang_hoa', max_length=50),
        ),
    ]
