# Generated by Django 2.1.15 on 2023-11-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanghoa', '0002_auto_20231112_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanghoa',
            name='so_luong',
            field=models.IntegerField(db_column='So_luong', null=True),
        ),
    ]
