# Generated by Django 2.1.15 on 2023-11-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nguoigiaohang',
            fields=[
                ('ma_ngh', models.CharField(db_column='Ma_NGH', max_length=10, primary_key=True, serialize=False)),
                ('ten_ngh', models.CharField(db_column='Ten_NGH', max_length=50)),
            ],
            options={
                'db_table': 'NguoiGiaoHang',
            },
        ),
    ]
