# Generated by Django 2.1.15 on 2023-11-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nhap',
            fields=[
                ('ma_phieu_nk', models.CharField(db_column='Ma_phieu_NK', max_length=10, primary_key=True, serialize=False)),
                ('ma_nguoi_giao_hang', models.CharField(db_column='Ma_nguoi_giao_hang', max_length=10)),
                ('thuc_nhap', models.IntegerField(db_column='Thuc_nhap')),
                ('tong_cong', models.IntegerField(db_column='Tong_cong')),
                ('ma_kho', models.ForeignKey(db_column='Ma_kho', default=None, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='kho.Kho')),
            ],
            options={
                'db_table': 'Nhap',
            },
        ),
    ]
