# Generated by Django 2.1.15 on 2023-11-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhap', '0002_auto_20231112_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhap',
            name='tong_cong',
            field=models.DecimalField(db_column='Tong_cong', decimal_places=0, max_digits=12),
        ),
    ]
