# Generated by Django 2.1.15 on 2023-11-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhap', '0004_auto_20231112_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhap',
            name='thuc_nhap',
            field=models.IntegerField(db_column='Thuc_nhap', null=True),
        ),
        migrations.AlterField(
            model_name='nhap',
            name='tong_cong',
            field=models.DecimalField(db_column='Tong_cong', decimal_places=0, max_digits=12, null=True),
        ),
    ]
