# Generated by Django 2.1.15 on 2023-11-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanghoa', '0003_auto_20231117_2118'),
        ('nhap', '0005_auto_20231117_2256'),
        ('nhapchitiet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phieunhapchitiet',
            new_name='Nhapchitiet',
        ),
        migrations.AlterModelTable(
            name='nhapchitiet',
            table='NhapChiTiet',
        ),
    ]
