# Generated by Django 2.1.15 on 2023-11-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('ma_kho', models.CharField(db_column='Ma_kho', max_length=10, primary_key=True, serialize=False)),
                ('dia_diem_kho', models.CharField(db_column='Dia_diem_kho', max_length=100)),
            ],
            options={
                'db_table': 'Kho',
            },
        ),
    ]
